DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS users;


CREATE TABLE images (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL ,
  mime_type VARCHAR(100) NOT NULL,
  public_id VARCHAR(255) NOT NULL UNIQUE,
  url_thumbnail VARCHAR(500) NOT NULL,
  url_medium VARCHAR(500) NOT NULL,
  url_large VARCHAR(500) NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  avatar VARCHAR(255) NOT NULL,
  full_name VARCHAR(200) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL, 
  phone VARCHAR(20) NOT NULL,
  role ENUM("ADMIN","USER") NOT NULL DEFAULT "USER",
  status ENUM('ACTIVE','INACTIVE','LOCKED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

